version: "3.4"

services:
  co-working:
    #    network_mode: host
    environment:
      - TZ=Asia/Bangkok
      - ASPNETCORE_ENVIRONMENT=Uat-Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8911:80"
    # volumes:
    #   - /root/draught-sit/volumes/Plupload:/app/wwwroot/Plupload
    #   - /root/draught-sit/volumes/uploads:/app/wwwroot/uploads
    restart: always
    extra_hosts:
      - "cow-uat.sbpds.co.th:10.7.9.201"
